---
- name: Avi SE | Services | upstart | Deploy the avise service
  copy: src=upstart/avise.conf dest=/etc/init/avise.conf mode=0644
  register: avise_service
  notify: Avi SE | Services | upstart | Restart the avise service
  when: new_service

- name: Avi SE | Services | upstart | Ensure the service has been started
  service: name=avise enabled=yes state=started
  register: start_service
