---
- name: Avi SE | Check minimum requirements
  include: docker/requirements.yml

- name: Avi SE | Perform specific os tasks
  include: docker/os/{{ ansible_distribution|lower }}.yml

- name: Avi SE | Perform specific os family tasks
  include: docker/family/{{ ansible_os_family|lower }}.yml

- name: Avi SE | Perform Docker tasks
  include: docker/main.yml

- name: Avi SE | Install DPDK
  include: docker/dpdk.yml
  when: dpdk

- name: Avi SE | Docker | Services | Service checks
  include: docker/services/check.yml

- name: Avi SE | Perform Autoregistration
  include: autoregistration.yml
  when: autoregister and avise_service_exists is not defined

- name: Avi SE | Docker | Services | Append the token to the docker environment variables.
  set_fact:
    env_variables_all: "{{ env_variables_all }} + ['AVICOOKIE={{ avi_token }}']"
  when: avi_token is defined

- name: Avi SE | Docker | Cleanup
  include: docker/services/cleanup.yml

- name: Avi SE | Install the Avi SE service
  include: docker/services/install.yml
