---
- name: Avi SE | Docker | Check if specified image already exists.
  shell: "docker images -q {{ se_image }}"
  changed_when: false
  register: docker_match

- block:
    - name: Avi SE | Docker | Deploy the image from the package
      copy: src={{ package_source }} dest={{ package_dest }}
    - name: Avi SE | Docker | Load the image from the package
      shell: "docker load -i {{ package_dest }}"
  when: package_deploy

- name: Avi SE | Docker | Load the image from docker hub
  shell: "docker pull {{ se_image }}"
  register: load_docker_hub
  changed_when: "'Status: Image is up to date' not in load_docker_hub.stdout"
  when:
    - docker_repo == None
    - not package_deploy
    - docker_match.stdout == "" or se_version == "latest"

- name: Avi SE | Docker | Load the image from custom docker repository
  shell: "docker pull {{ docker_repo }}/{{ se_image }}"
  register: load_docker_repo
  changed_when: "'Status: Image is up to date' not in load_docker_repo.stdout"
  when:
    - docker_repo != None
    - not package_deploy
    - docker_match.stdout == "" or se_version == "latest"

- name: Avi SE | Docker | Get our desired docker image id.
  shell: "docker images -q {{ se_image }}"
  changed_when: false
  register: docker_image

- name: Avi SE | Docker | Get list of running se containers
  shell: "docker ps -q -f name=avise"
  changed_when: false
  register: running_se_containers

- name: Avi SE | Docker | Check if desired version is already running.
  shell: "docker ps -q -f ancestor={{ docker_image.stdout }}"
  changed_when: false
  register: desired_running

- name: Avi SE | Check for existing avise service
  stat:
    path: "{{ item }}"
  register: service_installed
  with_items:
    - /etc/systemd/system/avise.service
    - /etc/init.d/avise

- name: Avi SE | Stop avise service
  service: name=avise enabled=no state=stopped
  when:
    - "{{ item.stat.exists }} == true"
    - desired_running.stdout == ""
  with_items: "{{ service_installed.results }}"


- name: Avi SE | Docker | Stop and Remove the container if it's not the desired version.
  shell: "docker stop {{ item }} && docker rm -f {{ item }}"
  with_items:
    - "{{ running_se_containers.stdout_lines }}"
  when:
    - item not in desired_running.stdout_lines
    - stopped_service.changed
