---
- name: Avi SE | Docker | Deploy the Avi SE image from the Package
  file: src={{ package_source }} dest={{ package_dest }}
  when: package_deploy

- name: Avi SE | Docker | Load the Avi SE image from the Package
  shell: "docker load -i {{ package_dest }}"
  when: package_deploy

- name: Avi SE | Docker | Load the Avi SE image from Docker Hub
  shell: "docker pull {{ se_image }}"
  when: docker_repo == None and not package_deploy

- name: Avi SE | Docker | Load the Avi SE image from custom Docker Repository
  shell: "docker pull {{ docker_repo }}/{{ se_image }}"
  when: docker_repo != None and not package_deploy

- name: Avi SE | Docker | Get list of running SE containers
  shell: "docker ps -f ancestor=avinetworks/se -q"
  register: running_se_containers

- name: Avi SE | Docker | Check if desired version is already running.
  shell: "docker ps -f ancestor={{ se_image }} -q"
  register: desired_running

- name: Avi SE | Docker | Stop and remove the container if it's not the desired version
  shell: "docker stop {{ item }} && docker rm -f {{ item }}"
  with_items:
    - "{{ running_se_containers.stdout_lines }}"
  when: item not in desired_running.stdout_lines
