---
# handlers for avinetworks.avise
- name: Avi SE | Services | systemd | Restart the avise service
  systemd: daemon_reload=yes name=avise enabled=yes state=restarted

- name: Avi SE | Services | upstart | Restart the avise service
  service: name=avise enabled=yes state=restarted

- name: Avi SE | Services | init.d | Restart the avise_watcher service
  service: name=avise_watcher enabled=yes state=restarted
