---
# - name: Avi SE | Docker | Services | Compare docker run parameters
#   set_fact:
#     docker_run_changed: "{{ existing_run_params != docker_run_params }}"
#   when: existing_run_params is defined
#
# - name: Avi SE | Docker | Cleanup | Stop avise_watcher service
#   service: name=avise_watcher enabled=no state=stopped
#   when:
#     - old_service
#     - docker_run_changed
#     - avise_service_exists is defined
#     - ansible_service_mgr != "systemd"
#
# - name: Avi SE | Docker | Cleanup | Stop avise service
#   service: name=avise enabled=no state=stopped
#   when:
#     - docker_run_changed
#     - avise_service_exists is defined

- name: Avi SE | Docker | Cleanup | Stop and Remove the container if it's not the desired version.
  shell: "docker stop {{ item }} && docker rm -f {{ item }}"
  when:
    - item not in desired_running.stdout_lines
  with_items:
    - "{{ running_se_containers.stdout_lines }}"
