---
- name: Avi SE | CSP | Metafile deploy | Setting the Avi metafile name
  set_fact:
    csp_se_metafile_name: avi_meta_{{ csp_service_name }}.yml

- name: Avi SE | CSP | Metafile deploy | Information
  debug: msg="Your metafile has been named {{ csp_se_metafile_name }}"

- name: Avi SE | CSP | Metafile deploy | See if the metafile already exists
  uri:
    url: "https://{{ inventory_hostname }}/api/operational/repository/image/{{ csp_se_metafile_name }}/_operations/get_image"
    method: POST
    user: "{{ csp_user }}"
    password: "{{ csp_password }}"
    force_basic_auth: yes
    headers:
      Accept: '*/*'
    validate_certs: false
    return_content: true
  failed_when: false
  register: avi_metafile_exists
  delegate_to: localhost

- block:
    - set_fact:
        avi_metafile_exists_json: "{{ avi_metafile_exists.content|from_json }}"
    - debug: msg="Metafile {{ avi_metafile_exists_json.output.name }} already exists."
  when: avi_metafile_exists.status == 200

- block:
    - name: Avi SE | CSP | Metafile deploy | Autoregistration
      include: autoregistration.yml
    - name: Avi SE | CSP | Autoregistration | Set csp_se_authtoken to auth_token
      set_fact:
        csp_se_authtoken: "{{ authtoken.obj.auth_token }}"
    - name: Avi SE | CSP | Metafile deploy | Create metafile content
      template:
        src: avi_meta_se.j2
        dest: /tmp/{{ csp_se_metafile_name }}
      delegate_to: localhost
      register: avi_metafile
    - name: Avi SE | CSP | Metafile deploy | Deploy metafile to the CSP device
      shell: sshpass -p {{ csp_password }} scp {{ avi_metafile.path }} {{ csp_user }}@{{ inventory_hostname }}:/osp/repository
      delegate_to: localhost
  when: avi_metafile_exists.status != 200
