---
- name: Avi SE | CSP | Requirements | Check variables
  assert:
    that:
      - "{{ item }} != None"
    msg: "{{ item }} must be provided"
  with_items:
    - csp_user
    - csp_password
    - csp_se_qcow_image_file
    - csp_se_qcow_image_name
    - csp_se_mgmt_ip
    - csp_se_mgmt_mask
    - csp_se_default_gw
    - master_ctl_ip
    - csp_se_tenant_uuid
    - csp_se_disk_size
    - csp_se_service_name
    - csp_se_num_cpu
    - csp_se_memory

- name: Avi SE | CSP | Requirements | Validate Sizing
  assert:
    that:
      - "{{ item.expr }}"
    msg: "{{ item.msg }}"
  with_items:
    - expr: csp_se_num_cpu|int >= 1
      msg: "Must have 1 or more CPU"
    - expr: csp_se_memory|int >= 1
      msg: "Must have 1GB or more memory"
    - expr: csp_se_disk_size|int >= 10
      msg: "Must have 10GB or more disk size"
