---
- set_fact:
    env_variables_extras: "{{ env_variables_extras + ['NON_SYSTEMD=1'] }}"

- name: Avi SE | Services | init.d | Deploy the avise service
  template: src=avise.j2 dest=/etc/init.d/avise mode=0744
  register: avise_service

- name: Avi SE | Services | init.d | Deploy the avise_watcher.sh script
  copy: src=avise_watcher.sh dest=/etc/init.d/avise_watcher.sh mode=0744
  register: avise_watcher_sh

- name: Avi SE | Services | init.d | Deploy the avise_watcher service
  copy: src=avise_watcher dest=/etc/init.d/avise_watcher mode=0744
  register: avise_watcher_service

- name: Avi SE | Services | init.d | Removing old rc links
  file: src=/etc/init.d/avise_watcher dest={{ item }} state=absent
  with_items:
    - /etc/rc0.d/K99avise
    - /etc/rc1.d/K99avise
    - /etc/rc2.d/S99avise
    - /etc/rc3.d/S99avise
    - /etc/rc4.d/S99avise
    - /etc/rc5.d/S99avise
    - /etc/rc6.d/K99avise

- name: Avi SE | Services | init.d | Deploying rc links
  file: src=/etc/init.d/avise_watcher dest={{ item }} state=link
  with_items:
    - /etc/rc0.d/K99avise_watcher
    - /etc/rc1.d/K99avise_watcher
    - /etc/rc2.d/S99avise_watcher
    - /etc/rc3.d/S99avise_watcher
    - /etc/rc4.d/S99avise_watcher
    - /etc/rc5.d/S99avise_watcher
    - /etc/rc6.d/K99avise_watcher

- name: Avi SE | Services | init.d | Restart the avise_watcher service
  service: name=avise_watcher enabled=yes state=restarted
  when: avise_service.changed or avise_watcher_service.changed or load_docker_repo.changed or load_docker_hub.changed

- name: Avi SE | Services | init.d | Start the avise_watcher service
  service: name=avise_watcher enabled=yes state=started
