---
- name: Avi SE | Deploy the avise service | init.d
  template: src=avise.j2 dest=/etc/init.d/avise mode=0744
  register: avise_service

- name: Avi SE | Deploying rc links | init.d
  file: src=/etc/init.d/avise dest={{ item }} state=link
  with_items:
    - /etc/rc0.d/K99avise
    - /etc/rc1.d/K99avise
    - /etc/rc2.d/S99avise
    - /etc/rc3.d/S99avise
    - /etc/rc4.d/S99avise
    - /etc/rc5.d/S99avise
    - /etc/rc6.d/K99avise

- name: Avi SE | Restart the avise service | init.d
  service: name=avise enabled=yes state=restarted
  when: avise_service.changed or load_docker_repo.changed or load_docker_hub.changed

- name: Avi SE | Start the avise service | init.d
  service: name=avise enabled=yes state=started
