---
- name: Deploy the avise service | init.d
  template: src=avise.j2 dest=/etc/init.d/avise mode=0744
  notify: Avi SE | Restart the Avi SE service | init.d

- name: Deploying rc links
  file: src=/etc/init.d/avise dest={{ item }} state=link
  with_items:
    - /etc/rc0.d/K99avise
    - /etc/rc1.d/K99avise
    - /etc/rc2.d/S99avise
    - /etc/rc3.d/S99avise
    - /etc/rc4.d/S99avise
    - /etc/rc5.d/S99avise
    - /etc/rc6.d/K99avise
