---
- name: Avi SE | Services | Install the Avi Service Engine systemd service
  include: systemd.yml
  when: ansible_service_mgr == 'systemd'

- name: Avi SE | Services | Install the Avi Service Engine upstart service
  include: upstart.yml
  when: ansible_service_mgr == 'upstart'

- name: Avi SE | Services | Install the Avi Service Engine init.d service
  include: initd.yml
  when: ansible_service_mgr == 'init'
