---
- name: Avi SE | Deploy the avise service | systemd
  template: src=avise.service.j2 dest=/etc/systemd/system/avise.service mode=0744
  register: avise_service

- name: Avi SE | Restart the avise service | systemd
  systemd: daemon_reload=yes name=avise enabled=yes state=restarted
  when: avise_service.changed or load_docker_repo.changed or load_docker_hub.changed

- name: Avi SE | Start the avise service | systemd
  systemd: daemon_reload=yes name=avise enabled=yes state=started
