---
- name: Avi SE | Services | systemd | 16.x | Deploy the avise service
  template:
    src: 16.x/avise.service.j2
    dest: /etc/systemd/system/avise.service
    mode: 0644
  register: avise_service
  notify: Avi SE | Services | systemd | Restart the avise service
  when:
    - old_service
    - docker_run_changed

- name: Avi SE | Services | systemd | 17.x | Deploy the avise service
  copy:
    src: systemd/avise.service
    dest: /etc/systemd/system/avise.service
    mode: 0644
  register: avise_service
  notify: Avi SE | Services | systemd | Restart the avise service
  when:
    - new_service
    - docker_run_changed

# Standard steps
- name: Avi SE | Services | systemd | Ensure the service has been started
  systemd: daemon_reload=yes name=avise enabled=yes state=started
  register: start_service
