---
# Default docker image pull from the Docker Hub.

- name: Avi SE | Docker | Load the image from Docker Hub
  shell: "docker pull {{ se_image }}"
  register: load_docker_hub
  changed_when: "'Status: Image is up to date' not in load_docker_hub.stdout"
  when: docker_match.stdout == "" or se_version == "latest"
